package Modelo;
// Generated 06-05-2018 17:41:07 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * AlojamientoId generated by hbm2java
 */
public class AlojamientoId  implements java.io.Serializable {


     private Date ingreso;
     private String rutPersona;
     private BigDecimal codigoCama;

    public AlojamientoId() {
    }

    public AlojamientoId(Date ingreso, String rutPersona, BigDecimal codigoCama) {
       this.ingreso = ingreso;
       this.rutPersona = rutPersona;
       this.codigoCama = codigoCama;
    }
   
    public Date getIngreso() {
        return this.ingreso;
    }
    
    public void setIngreso(Date ingreso) {
        this.ingreso = ingreso;
    }
    public String getRutPersona() {
        return this.rutPersona;
    }
    
    public void setRutPersona(String rutPersona) {
        this.rutPersona = rutPersona;
    }
    public BigDecimal getCodigoCama() {
        return this.codigoCama;
    }
    
    public void setCodigoCama(BigDecimal codigoCama) {
        this.codigoCama = codigoCama;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AlojamientoId) ) return false;
		 AlojamientoId castOther = ( AlojamientoId ) other; 
         
		 return ( (this.getIngreso()==castOther.getIngreso()) || ( this.getIngreso()!=null && castOther.getIngreso()!=null && this.getIngreso().equals(castOther.getIngreso()) ) )
 && ( (this.getRutPersona()==castOther.getRutPersona()) || ( this.getRutPersona()!=null && castOther.getRutPersona()!=null && this.getRutPersona().equals(castOther.getRutPersona()) ) )
 && ( (this.getCodigoCama()==castOther.getCodigoCama()) || ( this.getCodigoCama()!=null && castOther.getCodigoCama()!=null && this.getCodigoCama().equals(castOther.getCodigoCama()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIngreso() == null ? 0 : this.getIngreso().hashCode() );
         result = 37 * result + ( getRutPersona() == null ? 0 : this.getRutPersona().hashCode() );
         result = 37 * result + ( getCodigoCama() == null ? 0 : this.getCodigoCama().hashCode() );
         return result;
   }   


}


