package Modelo;
// Generated 06-05-2018 17:41:07 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Cama generated by hbm2java
 */
public class Cama  implements java.io.Serializable {


     private BigDecimal codigo;
     private String descripcion;
     private String disponible;
     private String codigoHabitacion;
     private Set alojamientos = new HashSet(0);

    public Cama() {
    }

	
    public Cama(BigDecimal codigo, String descripcion, String disponible, String codigoHabitacion) {
        this.codigo = codigo;
        this.descripcion = descripcion;
        this.disponible = disponible;
        this.codigoHabitacion = codigoHabitacion;
    }
    public Cama(BigDecimal codigo, String descripcion, String disponible, String codigoHabitacion, Set alojamientos) {
       this.codigo = codigo;
       this.descripcion = descripcion;
       this.disponible = disponible;
       this.codigoHabitacion = codigoHabitacion;
       this.alojamientos = alojamientos;
    }
   
    public BigDecimal getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(BigDecimal codigo) {
        this.codigo = codigo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getDisponible() {
        return this.disponible;
    }
    
    public void setDisponible(String disponible) {
        this.disponible = disponible;
    }
    public String getCodigoHabitacion() {
        return this.codigoHabitacion;
    }
    
    public void setCodigoHabitacion(String codigoHabitacion) {
        this.codigoHabitacion = codigoHabitacion;
    }
    public Set getAlojamientos() {
        return this.alojamientos;
    }
    
    public void setAlojamientos(Set alojamientos) {
        this.alojamientos = alojamientos;
    }




}


