package Modelo;
// Generated 06-05-2018 17:41:07 by Hibernate Tools 4.3.1



/**
 * CiudadId generated by hbm2java
 */
public class CiudadId  implements java.io.Serializable {


     private String nombre;
     private short codPais;

    public CiudadId() {
    }

    public CiudadId(String nombre, short codPais) {
       this.nombre = nombre;
       this.codPais = codPais;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public short getCodPais() {
        return this.codPais;
    }
    
    public void setCodPais(short codPais) {
        this.codPais = codPais;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CiudadId) ) return false;
		 CiudadId castOther = ( CiudadId ) other; 
         
		 return ( (this.getNombre()==castOther.getNombre()) || ( this.getNombre()!=null && castOther.getNombre()!=null && this.getNombre().equals(castOther.getNombre()) ) )
 && (this.getCodPais()==castOther.getCodPais());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNombre() == null ? 0 : this.getNombre().hashCode() );
         result = 37 * result + this.getCodPais();
         return result;
   }   


}


