package Modelo;
// Generated 06-05-2018 17:41:07 by Hibernate Tools 4.3.1



/**
 * Ciudad generated by hbm2java
 */
public class Ciudad  implements java.io.Serializable {


     private CiudadId id;
     private Pais pais;
     private int codArea;

    public Ciudad() {
    }

    public Ciudad(CiudadId id, Pais pais, int codArea) {
       this.id = id;
       this.pais = pais;
       this.codArea = codArea;
    }
   
    public CiudadId getId() {
        return this.id;
    }
    
    public void setId(CiudadId id) {
        this.id = id;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public int getCodArea() {
        return this.codArea;
    }
    
    public void setCodArea(int codArea) {
        this.codArea = codArea;
    }




}


