package Modelo;
// Generated 06-05-2018 17:41:07 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * ComidaId generated by hbm2java
 */
public class ComidaId  implements java.io.Serializable {


     private Date recepcion;
     private BigDecimal codigoPlato;
     private String rutPersona;

    public ComidaId() {
    }

    public ComidaId(Date recepcion, BigDecimal codigoPlato, String rutPersona) {
       this.recepcion = recepcion;
       this.codigoPlato = codigoPlato;
       this.rutPersona = rutPersona;
    }
   
    public Date getRecepcion() {
        return this.recepcion;
    }
    
    public void setRecepcion(Date recepcion) {
        this.recepcion = recepcion;
    }
    public BigDecimal getCodigoPlato() {
        return this.codigoPlato;
    }
    
    public void setCodigoPlato(BigDecimal codigoPlato) {
        this.codigoPlato = codigoPlato;
    }
    public String getRutPersona() {
        return this.rutPersona;
    }
    
    public void setRutPersona(String rutPersona) {
        this.rutPersona = rutPersona;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ComidaId) ) return false;
		 ComidaId castOther = ( ComidaId ) other; 
         
		 return ( (this.getRecepcion()==castOther.getRecepcion()) || ( this.getRecepcion()!=null && castOther.getRecepcion()!=null && this.getRecepcion().equals(castOther.getRecepcion()) ) )
 && ( (this.getCodigoPlato()==castOther.getCodigoPlato()) || ( this.getCodigoPlato()!=null && castOther.getCodigoPlato()!=null && this.getCodigoPlato().equals(castOther.getCodigoPlato()) ) )
 && ( (this.getRutPersona()==castOther.getRutPersona()) || ( this.getRutPersona()!=null && castOther.getRutPersona()!=null && this.getRutPersona().equals(castOther.getRutPersona()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRecepcion() == null ? 0 : this.getRecepcion().hashCode() );
         result = 37 * result + ( getCodigoPlato() == null ? 0 : this.getCodigoPlato().hashCode() );
         result = 37 * result + ( getRutPersona() == null ? 0 : this.getRutPersona().hashCode() );
         return result;
   }   


}


