package Modelo;
// Generated 06-05-2018 17:41:07 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private FacturaId id;
     private OrdenDeCompra ordenDeCompra;
     private OrdenDePedido ordenDePedido;
     private Date fecha;
     private int valorBruto;
     private int valorIva;
     private int valorNeto;
     private String observaciones;
     private String ubicacion;
     private String estado;

    public Factura() {
    }

	
    public Factura(FacturaId id, Date fecha, int valorBruto, int valorIva, int valorNeto, String ubicacion) {
        this.id = id;
        this.fecha = fecha;
        this.valorBruto = valorBruto;
        this.valorIva = valorIva;
        this.valorNeto = valorNeto;
        this.ubicacion = ubicacion;
    }
    public Factura(FacturaId id, OrdenDeCompra ordenDeCompra, OrdenDePedido ordenDePedido, Date fecha, int valorBruto, int valorIva, int valorNeto, String observaciones, String ubicacion, String estado) {
       this.id = id;
       this.ordenDeCompra = ordenDeCompra;
       this.ordenDePedido = ordenDePedido;
       this.fecha = fecha;
       this.valorBruto = valorBruto;
       this.valorIva = valorIva;
       this.valorNeto = valorNeto;
       this.observaciones = observaciones;
       this.ubicacion = ubicacion;
       this.estado = estado;
    }
   
    public FacturaId getId() {
        return this.id;
    }
    
    public void setId(FacturaId id) {
        this.id = id;
    }
    public OrdenDeCompra getOrdenDeCompra() {
        return this.ordenDeCompra;
    }
    
    public void setOrdenDeCompra(OrdenDeCompra ordenDeCompra) {
        this.ordenDeCompra = ordenDeCompra;
    }
    public OrdenDePedido getOrdenDePedido() {
        return this.ordenDePedido;
    }
    
    public void setOrdenDePedido(OrdenDePedido ordenDePedido) {
        this.ordenDePedido = ordenDePedido;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public int getValorBruto() {
        return this.valorBruto;
    }
    
    public void setValorBruto(int valorBruto) {
        this.valorBruto = valorBruto;
    }
    public int getValorIva() {
        return this.valorIva;
    }
    
    public void setValorIva(int valorIva) {
        this.valorIva = valorIva;
    }
    public int getValorNeto() {
        return this.valorNeto;
    }
    
    public void setValorNeto(int valorNeto) {
        this.valorNeto = valorNeto;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


