package Modelo;
// Generated 06-05-2018 17:41:07 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OrdenDeCompra generated by hbm2java
 */
public class OrdenDeCompra  implements java.io.Serializable {


     private BigDecimal numero;
     private Cliente cliente;
     private Date recepcion;
     private int monto;
     private String observaciones;
     private String ubicacion;
     private String estado;
     private Set alojamientos = new HashSet(0);
     private Set facturas = new HashSet(0);
     private Set comidas = new HashSet(0);

    public OrdenDeCompra() {
    }

	
    public OrdenDeCompra(BigDecimal numero, Cliente cliente, Date recepcion, int monto) {
        this.numero = numero;
        this.cliente = cliente;
        this.recepcion = recepcion;
        this.monto = monto;
    }
    public OrdenDeCompra(BigDecimal numero, Cliente cliente, Date recepcion, int monto, String observaciones, String ubicacion, String estado, Set alojamientos, Set facturas, Set comidas) {
       this.numero = numero;
       this.cliente = cliente;
       this.recepcion = recepcion;
       this.monto = monto;
       this.observaciones = observaciones;
       this.ubicacion = ubicacion;
       this.estado = estado;
       this.alojamientos = alojamientos;
       this.facturas = facturas;
       this.comidas = comidas;
    }
   
    public BigDecimal getNumero() {
        return this.numero;
    }
    
    public void setNumero(BigDecimal numero) {
        this.numero = numero;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Date getRecepcion() {
        return this.recepcion;
    }
    
    public void setRecepcion(Date recepcion) {
        this.recepcion = recepcion;
    }
    public int getMonto() {
        return this.monto;
    }
    
    public void setMonto(int monto) {
        this.monto = monto;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getAlojamientos() {
        return this.alojamientos;
    }
    
    public void setAlojamientos(Set alojamientos) {
        this.alojamientos = alojamientos;
    }
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }
    public Set getComidas() {
        return this.comidas;
    }
    
    public void setComidas(Set comidas) {
        this.comidas = comidas;
    }




}


