package Modelo;
// Generated 06-05-2018 17:41:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pais generated by hbm2java
 */
public class Pais  implements java.io.Serializable {


     private short codigo;
     private String nombre;
     private Set ciudads = new HashSet(0);
     private Set personas = new HashSet(0);

    public Pais() {
    }

	
    public Pais(short codigo, String nombre) {
        this.codigo = codigo;
        this.nombre = nombre;
    }
    public Pais(short codigo, String nombre, Set ciudads, Set personas) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.ciudads = ciudads;
       this.personas = personas;
    }
   
    public short getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(short codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getCiudads() {
        return this.ciudads;
    }
    
    public void setCiudads(Set ciudads) {
        this.ciudads = ciudads;
    }
    public Set getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set personas) {
        this.personas = personas;
    }




}


