package Modelo;
// Generated 06-05-2018 17:41:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private short codigo;
     private String descripcion;
     private int precio;
     private short stock;
     private byte stockCritico;
     private Set rrps = new HashSet(0);

    public Producto() {
    }

	
    public Producto(short codigo, String descripcion, int precio, short stock, byte stockCritico) {
        this.codigo = codigo;
        this.descripcion = descripcion;
        this.precio = precio;
        this.stock = stock;
        this.stockCritico = stockCritico;
    }
    public Producto(short codigo, String descripcion, int precio, short stock, byte stockCritico, Set rrps) {
       this.codigo = codigo;
       this.descripcion = descripcion;
       this.precio = precio;
       this.stock = stock;
       this.stockCritico = stockCritico;
       this.rrps = rrps;
    }
   
    public short getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(short codigo) {
        this.codigo = codigo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(int precio) {
        this.precio = precio;
    }
    public short getStock() {
        return this.stock;
    }
    
    public void setStock(short stock) {
        this.stock = stock;
    }
    public byte getStockCritico() {
        return this.stockCritico;
    }
    
    public void setStockCritico(byte stockCritico) {
        this.stockCritico = stockCritico;
    }
    public Set getRrps() {
        return this.rrps;
    }
    
    public void setRrps(Set rrps) {
        this.rrps = rrps;
    }




}


