package Modelo;
// Generated 06-05-2018 17:41:07 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Rrp generated by hbm2java
 */
public class Rrp  implements java.io.Serializable {


     private RrpId id;
     private OrdenDePedido ordenDePedido;
     private Producto producto;
     private Date recepcion;

    public Rrp() {
    }

    public Rrp(RrpId id, OrdenDePedido ordenDePedido, Producto producto, Date recepcion) {
       this.id = id;
       this.ordenDePedido = ordenDePedido;
       this.producto = producto;
       this.recepcion = recepcion;
    }
   
    public RrpId getId() {
        return this.id;
    }
    
    public void setId(RrpId id) {
        this.id = id;
    }
    public OrdenDePedido getOrdenDePedido() {
        return this.ordenDePedido;
    }
    
    public void setOrdenDePedido(OrdenDePedido ordenDePedido) {
        this.ordenDePedido = ordenDePedido;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Date getRecepcion() {
        return this.recepcion;
    }
    
    public void setRecepcion(Date recepcion) {
        this.recepcion = recepcion;
    }




}


