package Modelo.Clases;
// Generated 21-may-2018 21:37:47 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Alojamiento generated by hbm2java
 */
public class Alojamiento  implements java.io.Serializable {


     private AlojamientoId id;
     private Cama cama;
     private OrdenDeCompra ordenDeCompra;
     private Persona persona;
     private Date egreso;
     private Short registroDias;
     private String observaciones;
     private String confirmado;

    public Alojamiento() {
    }

	
    public Alojamiento(AlojamientoId id, Cama cama, Persona persona) {
        this.id = id;
        this.cama = cama;
        this.persona = persona;
    }
    public Alojamiento(AlojamientoId id, Cama cama, OrdenDeCompra ordenDeCompra, Persona persona, Date egreso, Short registroDias, String observaciones, String confirmado) {
       this.id = id;
       this.cama = cama;
       this.ordenDeCompra = ordenDeCompra;
       this.persona = persona;
       this.egreso = egreso;
       this.registroDias = registroDias;
       this.observaciones = observaciones;
       this.confirmado = confirmado;
    }
   
    public AlojamientoId getId() {
        return this.id;
    }
    
    public void setId(AlojamientoId id) {
        this.id = id;
    }
    public Cama getCama() {
        return this.cama;
    }
    
    public void setCama(Cama cama) {
        this.cama = cama;
    }
    public OrdenDeCompra getOrdenDeCompra() {
        return this.ordenDeCompra;
    }
    
    public void setOrdenDeCompra(OrdenDeCompra ordenDeCompra) {
        this.ordenDeCompra = ordenDeCompra;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Date getEgreso() {
        return this.egreso;
    }
    
    public void setEgreso(Date egreso) {
        this.egreso = egreso;
    }
    public Short getRegistroDias() {
        return this.registroDias;
    }
    
    public void setRegistroDias(Short registroDias) {
        this.registroDias = registroDias;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public String getConfirmado() {
        return this.confirmado;
    }
    
    public void setConfirmado(String confirmado) {
        this.confirmado = confirmado;
    }




}


