package Modelo.Clases;
// Generated 21-may-2018 21:37:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private String rut;
     private Empresa empresa;
     private Set ordenDeCompras = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(Empresa empresa) {
        this.empresa = empresa;
    }
    public Cliente(Empresa empresa, Set ordenDeCompras) {
       this.empresa = empresa;
       this.ordenDeCompras = ordenDeCompras;
    }
   
    public String getRut() {
        return this.rut;
    }
    
    public void setRut(String rut) {
        this.rut = rut;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public Set getOrdenDeCompras() {
        return this.ordenDeCompras;
    }
    
    public void setOrdenDeCompras(Set ordenDeCompras) {
        this.ordenDeCompras = ordenDeCompras;
    }




}


