package Modelo.Clases;
// Generated 22-may-2018 23:54:46 by Hibernate Tools 4.3.1



/**
 * Comida generated by hbm2java
 */
public class Comida  implements java.io.Serializable {


     private ComidaId id;
     private OrdenDeCompra ordenDeCompra;
     private Persona persona;
     private Plato plato;
     private String observaciones;
     private String confirmada;

    public Comida() {
    }

	
    public Comida(ComidaId id, Persona persona, Plato plato) {
        this.id = id;
        this.persona = persona;
        this.plato = plato;
    }
    public Comida(ComidaId id, OrdenDeCompra ordenDeCompra, Persona persona, Plato plato, String observaciones, String confirmada) {
       this.id = id;
       this.ordenDeCompra = ordenDeCompra;
       this.persona = persona;
       this.plato = plato;
       this.observaciones = observaciones;
       this.confirmada = confirmada;
    }
   
    public ComidaId getId() {
        return this.id;
    }
    
    public void setId(ComidaId id) {
        this.id = id;
    }
    public OrdenDeCompra getOrdenDeCompra() {
        return this.ordenDeCompra;
    }
    
    public void setOrdenDeCompra(OrdenDeCompra ordenDeCompra) {
        this.ordenDeCompra = ordenDeCompra;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Plato getPlato() {
        return this.plato;
    }
    
    public void setPlato(Plato plato) {
        this.plato = plato;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public String getConfirmada() {
        return this.confirmada;
    }
    
    public void setConfirmada(String confirmada) {
        this.confirmada = confirmada;
    }




}


