package Modelo.Clases;
// Generated 22-may-2018 23:54:46 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * FacturaId generated by hbm2java
 */
public class FacturaId  implements java.io.Serializable {


     private String tipo;
     private BigDecimal numero;

    public FacturaId() {
    }

    public FacturaId(String tipo, BigDecimal numero) {
       this.tipo = tipo;
       this.numero = numero;
    }
   
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public BigDecimal getNumero() {
        return this.numero;
    }
    
    public void setNumero(BigDecimal numero) {
        this.numero = numero;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FacturaId) ) return false;
		 FacturaId castOther = ( FacturaId ) other; 
         
		 return ( (this.getTipo()==castOther.getTipo()) || ( this.getTipo()!=null && castOther.getTipo()!=null && this.getTipo().equals(castOther.getTipo()) ) )
 && ( (this.getNumero()==castOther.getNumero()) || ( this.getNumero()!=null && castOther.getNumero()!=null && this.getNumero().equals(castOther.getNumero()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTipo() == null ? 0 : this.getTipo().hashCode() );
         result = 37 * result + ( getNumero() == null ? 0 : this.getNumero().hashCode() );
         return result;
   }   


}


