package Modelo.Clases;
// Generated 21-may-2018 21:37:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Habitacion generated by hbm2java
 */
public class Habitacion  implements java.io.Serializable {


     private short codigo;
     private String estado;
     private boolean capacidad;
     private String descripcion;
     private int precio;
     private Set camas = new HashSet(0);

    public Habitacion() {
    }

	
    public Habitacion(short codigo, String estado, boolean capacidad, int precio) {
        this.codigo = codigo;
        this.estado = estado;
        this.capacidad = capacidad;
        this.precio = precio;
    }
    public Habitacion(short codigo, String estado, boolean capacidad, String descripcion, int precio, Set camas) {
       this.codigo = codigo;
       this.estado = estado;
       this.capacidad = capacidad;
       this.descripcion = descripcion;
       this.precio = precio;
       this.camas = camas;
    }
   
    public short getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(short codigo) {
        this.codigo = codigo;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public boolean isCapacidad() {
        return this.capacidad;
    }
    
    public void setCapacidad(boolean capacidad) {
        this.capacidad = capacidad;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(int precio) {
        this.precio = precio;
    }
    public Set getCamas() {
        return this.camas;
    }
    
    public void setCamas(Set camas) {
        this.camas = camas;
    }




}


