package Modelo.Clases;
// Generated 21-may-2018 21:37:47 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OrdenDePedido generated by hbm2java
 */
public class OrdenDePedido  implements java.io.Serializable {


     private BigDecimal numero;
     private Proveedor proveedor;
     private Date emision;
     private int monto;
     private String observaciones;
     private String ubicacion;
     private String estado;
     private Set rrps = new HashSet(0);
     private Set facturas = new HashSet(0);

    public OrdenDePedido() {
    }

	
    public OrdenDePedido(BigDecimal numero, Proveedor proveedor, Date emision, int monto) {
        this.numero = numero;
        this.proveedor = proveedor;
        this.emision = emision;
        this.monto = monto;
    }
    public OrdenDePedido(BigDecimal numero, Proveedor proveedor, Date emision, int monto, String observaciones, String ubicacion, String estado, Set rrps, Set facturas) {
       this.numero = numero;
       this.proveedor = proveedor;
       this.emision = emision;
       this.monto = monto;
       this.observaciones = observaciones;
       this.ubicacion = ubicacion;
       this.estado = estado;
       this.rrps = rrps;
       this.facturas = facturas;
    }
   
    public BigDecimal getNumero() {
        return this.numero;
    }
    
    public void setNumero(BigDecimal numero) {
        this.numero = numero;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public Date getEmision() {
        return this.emision;
    }
    
    public void setEmision(Date emision) {
        this.emision = emision;
    }
    public int getMonto() {
        return this.monto;
    }
    
    public void setMonto(int monto) {
        this.monto = monto;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getRrps() {
        return this.rrps;
    }
    
    public void setRrps(Set rrps) {
        this.rrps = rrps;
    }
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }




}


