package Modelo.Clases;
// Generated 22-may-2018 23:54:46 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Pago generated by hbm2java
 */
public class Pago  implements java.io.Serializable {


     private PagoId id;
     private Factura factura;
     private String medioPago;
     private String divisa;
     private String codigoIso;
     private String monto;
     private BigDecimal tasaCambioClp;

    public Pago() {
    }

	
    public Pago(Factura factura, String medioPago, String codigoIso) {
        this.factura = factura;
        this.medioPago = medioPago;
        this.codigoIso = codigoIso;
    }
    public Pago(Factura factura, String medioPago, String divisa, String codigoIso, String monto, BigDecimal tasaCambioClp) {
       this.factura = factura;
       this.medioPago = medioPago;
       this.divisa = divisa;
       this.codigoIso = codigoIso;
       this.monto = monto;
       this.tasaCambioClp = tasaCambioClp;
    }
   
    public PagoId getId() {
        return this.id;
    }
    
    public void setId(PagoId id) {
        this.id = id;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public String getMedioPago() {
        return this.medioPago;
    }
    
    public void setMedioPago(String medioPago) {
        this.medioPago = medioPago;
    }
    public String getDivisa() {
        return this.divisa;
    }
    
    public void setDivisa(String divisa) {
        this.divisa = divisa;
    }
    public String getCodigoIso() {
        return this.codigoIso;
    }
    
    public void setCodigoIso(String codigoIso) {
        this.codigoIso = codigoIso;
    }
    public String getMonto() {
        return this.monto;
    }
    
    public void setMonto(String monto) {
        this.monto = monto;
    }
    public BigDecimal getTasaCambioClp() {
        return this.tasaCambioClp;
    }
    
    public void setTasaCambioClp(BigDecimal tasaCambioClp) {
        this.tasaCambioClp = tasaCambioClp;
    }




}


