package Modelo.Clases;
// Generated 22-may-2018 23:54:46 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Plato generated by hbm2java
 */
public class Plato  implements java.io.Serializable {


     private BigDecimal codigo;
     private ServicioComida servicioComida;
     private String nombre;
     private String descripcion;
     private String disponible;
     private Set comidas = new HashSet(0);

    public Plato() {
    }

	
    public Plato(BigDecimal codigo, ServicioComida servicioComida, String nombre, String descripcion, String disponible) {
        this.codigo = codigo;
        this.servicioComida = servicioComida;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.disponible = disponible;
    }
    public Plato(BigDecimal codigo, ServicioComida servicioComida, String nombre, String descripcion, String disponible, Set comidas) {
       this.codigo = codigo;
       this.servicioComida = servicioComida;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.disponible = disponible;
       this.comidas = comidas;
    }
   
    public BigDecimal getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(BigDecimal codigo) {
        this.codigo = codigo;
    }
    public ServicioComida getServicioComida() {
        return this.servicioComida;
    }
    
    public void setServicioComida(ServicioComida servicioComida) {
        this.servicioComida = servicioComida;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getDisponible() {
        return this.disponible;
    }
    
    public void setDisponible(String disponible) {
        this.disponible = disponible;
    }
    public Set getComidas() {
        return this.comidas;
    }
    
    public void setComidas(Set comidas) {
        this.comidas = comidas;
    }




}


