package Modelo.Clases;
// Generated 21-may-2018 21:37:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private String rut;
     private Empresa empresa;
     private Set ordenDePedidos = new HashSet(0);

    public Proveedor() {
    }

	
    public Proveedor(Empresa empresa) {
        this.empresa = empresa;
    }
    public Proveedor(Empresa empresa, Set ordenDePedidos) {
       this.empresa = empresa;
       this.ordenDePedidos = ordenDePedidos;
    }
   
    public String getRut() {
        return this.rut;
    }
    
    public void setRut(String rut) {
        this.rut = rut;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public Set getOrdenDePedidos() {
        return this.ordenDePedidos;
    }
    
    public void setOrdenDePedidos(Set ordenDePedidos) {
        this.ordenDePedidos = ordenDePedidos;
    }




}


