package Modelo.Clases;
// Generated 22-may-2018 23:54:46 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Rrp generated by hbm2java
 */
public class Rrp  implements java.io.Serializable {


     private RrpId id;
     private OrdenDePedido ordenDePedido;
     private Producto producto;
     private Date recepcion;
     private String confirmado;

    public Rrp() {
    }

	
    public Rrp(RrpId id, OrdenDePedido ordenDePedido, Producto producto, Date recepcion) {
        this.id = id;
        this.ordenDePedido = ordenDePedido;
        this.producto = producto;
        this.recepcion = recepcion;
    }
    public Rrp(RrpId id, OrdenDePedido ordenDePedido, Producto producto, Date recepcion, String confirmado) {
       this.id = id;
       this.ordenDePedido = ordenDePedido;
       this.producto = producto;
       this.recepcion = recepcion;
       this.confirmado = confirmado;
    }
   
    public RrpId getId() {
        return this.id;
    }
    
    public void setId(RrpId id) {
        this.id = id;
    }
    public OrdenDePedido getOrdenDePedido() {
        return this.ordenDePedido;
    }
    
    public void setOrdenDePedido(OrdenDePedido ordenDePedido) {
        this.ordenDePedido = ordenDePedido;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Date getRecepcion() {
        return this.recepcion;
    }
    
    public void setRecepcion(Date recepcion) {
        this.recepcion = recepcion;
    }
    public String getConfirmado() {
        return this.confirmado;
    }
    
    public void setConfirmado(String confirmado) {
        this.confirmado = confirmado;
    }




}


