package Modelo.Clases;
// Generated 21-may-2018 21:37:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ServicioComida generated by hbm2java
 */
public class ServicioComida  implements java.io.Serializable {


     private String tipo;
     private Short precio;
     private Set platos = new HashSet(0);

    public ServicioComida() {
    }

	
    public ServicioComida(String tipo) {
        this.tipo = tipo;
    }
    public ServicioComida(String tipo, Short precio, Set platos) {
       this.tipo = tipo;
       this.precio = precio;
       this.platos = platos;
    }
   
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Short getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Short precio) {
        this.precio = precio;
    }
    public Set getPlatos() {
        return this.platos;
    }
    
    public void setPlatos(Set platos) {
        this.platos = platos;
    }




}


